---
- name: apply common configuration
  hosts: java
  become: yes
  become_method: sudo
  vars:
    #variable needed during node installation
  roles:
    - common

- name: configure and install tree
  hosts: tree
  become: yes
  become_method: sudo
  vars:
    #variable needed during node installation
  roles:
    - tree

- name: configure and install git
  hosts: git
  become: yes
  become_method: sudo
  vars:
    #variable needed during node installation
  roles:
    - git



